name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Flutter action
      uses: subosito/flutter-action@v1.3.2
      with:
        # The Flutter version to make available on the path
        flutter-version: '1.12.x' # optional
        # The Flutter build release channel
        channel: 'stable' # optional, default is stable
    - name: Install dependencies
      run: flutter pub get
    
    - name: Run tests
      run: flutter test
      
